# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filtered_image',
            field=models.ImageField(blank=True, upload_to='images/filtered/'),
        ),
    ]
