# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(choices=[('none', 'NONE'), ('blur', 'BLUR'), ('contour', 'CONTOUR'), ('detail', 'DETAIL'), ('enhance', 'EDGE_ENHANCE'), ('emboss', 'EMBOSS'), ('smoothen', 'SMOOTH'), ('sharpen', 'SHARPEN'), ('flip', 'FLIP'), ('grayscale', 'GRAYSCALE '), ('find edges', 'FIND_EDGES')], max_length=100)),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('filteredimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_v1.FilteredImage')),
            ],
            bases=('api_v1.filteredimage',),
        ),
        migrations.AddField(
            model_name='filteredimage',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_images', to='api_v1.Image'),
        ),
    ]
