# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 12:58
from __future__ import unicode_literals

import api_v1.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20160711_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filtered_image',
            field=models.ImageField(blank=True, storage=api_v1.custom_storage.CustomStorage(), upload_to='images/filtered/'),
        ),
    ]
