# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailimage',
            name='filter_name',
            field=models.CharField(choices=[('NONE', 'none'), ('BLUR', 'blur'), ('CONTOUR', 'contour'), ('DETAIL', 'detail'), ('EDGE_ENHANCE', 'edge enhance'), ('EMBOSS', 'emboss'), ('SMOOTH', 'smoothen'), ('SHARPEN', 'sharpen'), ('FLIP', 'flip'), ('GRAYSCALE', 'grayscale'), ('FIND_EDGES', 'find edges')], default='NONE', max_length=100),
        ),
    ]
