# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_thumbnailimage_filter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered', models.ImageField(upload_to='images/thumbnails/')),
                ('filter_name', models.CharField(choices=[('NONE', 'none'), ('BLUR', 'blur'), ('CONTOUR', 'contour'), ('DETAIL', 'detail'), ('EDGE_ENHANCE', 'edge enhance'), ('EMBOSS', 'emboss'), ('SMOOTH', 'smoothen'), ('SHARPEN', 'sharpen'), ('FLIP', 'flip'), ('GRAYSCALE', 'grayscale'), ('FIND_EDGES', 'find edges')], default='NONE', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='thumbnailimage',
            name='filter_name',
        ),
        migrations.AddField(
            model_name='thumbnailfilter',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='api_v1.ThumbnailImage'),
        ),
    ]
