# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_auto_20160713_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnailfilter',
            old_name='filter_name',
            new_name='applied_filter',
        ),
    ]
